"""empty message

Revision ID: 36f91275550e
Revises: 
Create Date: 2025-06-01 18:07:53.997708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '36f91275550e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicacion')
    op.drop_table('usuario')
    op.drop_table('comentario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentario',
    sa.Column('id_comentario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_publicacion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicacion.id_publicacion'], name=op.f('fk_comentario_publicacion')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('fk_comentario_usuario')),
    sa.PrimaryKeyConstraint('id_comentario', name=op.f('comentario_pkey'))
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.INTEGER(), server_default=sa.text("nextval('usuario_id_usuario_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contrasenia', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'::text", name='usuario_email_check'),
    sa.PrimaryKeyConstraint('id_usuario', name='usuario_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('publicacion',
    sa.Column('id_publicacion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name=op.f('fk_publicacion_usuario')),
    sa.PrimaryKeyConstraint('id_publicacion', name=op.f('publicacion_pkey'))
    )
    # ### end Alembic commands ###
